name: MooVES
author: FirebUntU
category: Media
tags: [video, mootools, mooves, flash, embed, object, html5, thumbnail, preview]
docs: http://mooves.firebuntu.com/docs
demo: http://mooves.firebuntu.com/
